### PR TITLE
Update Tock to 1.5-rc2

### PR DESCRIPTION
**Pull request by jrvanwhy**
As part of testing the Tock 1.5 release candidates, this updates tock-on-titan to the latest release candidate.

```
----------------------
`make prtest` summary:
----------------------
git rev-parse HEAD
792b39206f387ee8aa07c11fac82399c5dc76f41
git status
On branch tock-1.5-rc
Your branch is up to date with 'origin/tock-1.5-rc'.

nothing to commit, working tree clean
```

### CODE REVIEW

**Comment by jrvanwhy** [comment]
Hmm, it appears something broken in the board Makefiles that only causes an error in clean builds. I'm investigating now.

**Comment by jrvanwhy** [comment]
I found the broken build issue, and it appears that I wasn't building any kernel code for a while without noticing. I probably still need to do some work on this to bring it all the way up to 1.5-rc2 again.

I'll hit "ready for review" when I have it up to date. Because I moved the kernel crates around, the delta for the commit updating to Tock ba44dd69 is large. This may be a PR to review commit-by-commit.

**Comment by osenft** [comment]
> I'll hit "ready for review" when I have it up to date.

SG, thank you! I was just talking with gdk@ about Tock 1.5 and that it would be beneficial to have this available for the Papa work. Thanks for taking this upgrade on!

**Comment by jrvanwhy** [comment]
> > I'll hit "ready for review" when I have it up to date.
> 
> SG, thank you! I was just talking with gdk@ about Tock 1.5 and that it would be beneficial to have this available for the Papa work. Thanks for taking this upgrade on!

Because I'm a Tock core developer I'm asked to test + sign off on new Tock releases. IMO, updating tock-on-titan is the best way I have to test new releases.

**Comment by jrvanwhy** [comment]
I thought there would be more remaining work to do, but this is ready for review again.

**Review by osenft — APPROVED** [review]

**Pull request merged**
